apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anything-llm-storage
  labels:
    app.kubernetes.io/name: anything-llm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
