apiVersion: v1
kind: Secret
metadata:
  name: anything-llm-secret
  labels:
    app.kubernetes.io/name: anything-llm
type: Opaque
stringData:
  JWT_SECRET: "anythingllm-dev-jwt-secret-rke2-gitops-token-key-2026"
