apiVersion: ENC[AES256_GCM,data:XEA=,iv:dzxrgDxBDD3F5G4wo6tXFSkPNZ8VMT/wv83q18xi6oM=,tag:1vdh9eO8EtCmtE89QB3DPg==,type:str]
kind: ENC[AES256_GCM,data:4Xc2jpcN,iv:FbpBOeOc7QlNd2Eeno8BaLN846veeMi0rGNXmZWCuuI=,tag:XccRJFtnv96CvJTbJ99PJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7oJ1IME4Gy6cHWk3h4p9FNkdG3E=,iv:5ae1Ci/zklH4r2s9+784Gv869/llb+nO2nKfO6eNgz4=,tag:uFKlEywno/9YOgbSRVWPsw==,type:str]
    namespace: ENC[AES256_GCM,data:YK8PG7aJe7OSZw==,iv:4XZQ4AJCKAQTDX10JZO+2mHRto2YeXndjr2RTDsesbw=,tag:kwZmHV9JPUsxJtfmZNgPgg==,type:str]
type: ENC[AES256_GCM,data:HcGJ4JC3,iv:JrilXLE7wMOOS1qT9Bt6J5AvIc/LrImw9BvOB034MvY=,tag:DFpXe4cutozPs1mbKhWJhQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:auDoRaQ=,iv:fasinxqLy8vYqN3lW7pRhrXYso6d05gOmb91Lc+qr/I=,tag:4RxF9O2occ3EjSxMc1MlpQ==,type:str]
    admin-password: ENC[AES256_GCM,data:8SSupeGT7b9YTmwJcDZ4t/E5,iv:WtiJIgJYFxhb2/x6O2A5KN9EZSTCxVl/basaPMR321A=,tag:NwQ5hgFDxowVPH+78dyDRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuU3VRcy9jNmRIVE9GSnRp
            dWZBK3pRMmZUaHAwT3dyTW45TnY4a1Q5dFg4Citab0N6Z2JKUUhveGNqK3AzaWpi
            WXBuaWMvU2dUTWYxQUIwbC9XK2l6NWsKLS0tIEZlYTNtS2JUazFFQTFZVnRUUFJS
            NThTeWlXbFdlb3FreWZpb3ZGbDh3aWsKNd/neN8RqhSDjc9MfnvpjCsYirzuI08k
            770TiZI/hFVgG/3pepMw9cEtZ75TGex10OiC1Lc9GC4GpKHLMKqIOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13hphavvlee240rq0j42j60mqxj8s4k9tp473g076xl5z35p8mgjqx29stw
    lastmodified: "2026-10-09T15:37:13Z"
    mac: ENC[AES256_GCM,data:qjq/tNYggQjztAxyEw3l7i3tHFjfdRyStJaZx4cHXcA8ksGtTfZSR003DZ5JoygDdWn0uRKenkVldrCQCGqdo2GGEzCtcZTQX2Kua9XiDXldnP8uiYLJxhsVVCMzyPSZpHHjuZg0xNKOuZ4ydOZdgel2tkRUjL9mlv0gak9VRRU=,iv:eA+tLcqsZSx+VeVsu0kGcA/E0iO/MT9qtOExGm8tN+g=,tag:iKIXdl2bQ7Nz1TVUW/WA0g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
