apiVersion: viaduct.ai/v1
kind: KSOPS
metadata:
  name: grafana-admin-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./grafana-secret.sops.yaml
