apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-demo-staging

resources:
  - ../../base

labels:
  - pairs:
      environment: staging

replicas:
  - name: nginx-demo
    count: 2

patches:
  - path: patch-ingress.yaml
