apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-ce-worker-wl
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: plane-ce-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane
        app.kubernetes.io/component: worker
        app.name: plane-ce-worker
    spec:
      serviceAccountName: plane-ce-srv-account
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z -w 2 plane-ce-pgdb 5432; do
                echo "Waiting for PostgreSQL database on port 5432...";
                sleep 2;
              done
      containers:
        - name: plane-ce-worker
          image: artifacts.plane.so/makeplane/plane-backend:v1.4.2
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
          command:
            - ./bin/docker-entrypoint-worker.sh
          envFrom:
            - configMapRef:
                name: plane-ce-app-vars
            - secretRef:
                name: plane-ce-app-secrets
            - secretRef:
                name: plane-ce-doc-store-secrets
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 3072Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plane-ce-beat-worker-wl
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/component: beat-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: plane-ce-beat-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plane
        app.kubernetes.io/component: beat-worker
        app.name: plane-ce-beat-worker
    spec:
      serviceAccountName: plane-ce-srv-account
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z -w 2 plane-ce-pgdb 5432; do
                echo "Waiting for PostgreSQL database on port 5432...";
                sleep 2;
              done
      containers:
        - name: plane-ce-beat-worker
          image: artifacts.plane.so/makeplane/plane-backend:v1.4.2
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
          command:
            - ./bin/docker-entrypoint-beat.sh
          envFrom:
            - configMapRef:
                name: plane-ce-app-vars
            - secretRef:
                name: plane-ce-app-secrets
            - secretRef:
                name: plane-ce-doc-store-secrets
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 1024Mi
