apiVersion: v1
kind: Secret
metadata:
  name: plane-ce-app-secrets
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: plane-ce
type: Opaque
stringData:
  SECRET_KEY: "plane-ce-dev-secret-key-rke2-gitops-2026-secure-random"
  LIVE_SERVER_SECRET_KEY: "plane-ce-live-dev-secret-key-rke2-gitops-2026"
  REDIS_URL: "redis://plane-ce-redis:6379/"
  DATABASE_URL: "postgresql://plane:plane@plane-ce-pgdb:5432/plane"
  AMQP_URL: "amqp://plane:plane@plane-ce-rabbitmq:5672/"
  # Plane AI Configurations & Placeholders
  OPENAI_API_KEY: "placeholder-openai-api-key-replace-me"
  OPENAI_API_BASE: "https://api.openai.com/v1"
  GPT_MODEL: "gpt-4o-mini"
  EMBEDDING_MODEL: "text-embedding-3-small"
---
apiVersion: v1
kind: Secret
metadata:
  name: plane-ce-live-secrets
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: plane-ce
type: Opaque
stringData:
  LIVE_SERVER_SECRET_KEY: "plane-ce-live-dev-secret-key-rke2-gitops-2026"
  REDIS_URL: "redis://plane-ce-redis:6379/"
---
apiVersion: v1
kind: Secret
metadata:
  name: plane-ce-doc-store-secrets
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: plane-ce
type: Opaque
stringData:
  FILE_SIZE_LIMIT: "52428800" # 50 MB
  AWS_S3_BUCKET_NAME: "uploads"
  USE_MINIO: "1"
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "PlaneMinioPassword2026!"
  AWS_ACCESS_KEY_ID: "admin"
  AWS_SECRET_ACCESS_KEY: "PlaneMinioPassword2026!"
  AWS_S3_ENDPOINT_URL: "http://plane-ce-minio:9000"
---
apiVersion: v1
kind: Secret
metadata:
  name: plane-ce-pgdb-secrets
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: plane-ce
type: Opaque
stringData:
  POSTGRES_USER: "plane"
  POSTGRES_PASSWORD: "plane"
  POSTGRES_DB: "plane"
---
apiVersion: v1
kind: Secret
metadata:
  name: plane-ce-rabbitmq-secrets
  labels:
    app.kubernetes.io/name: plane
    app.kubernetes.io/part-of: plane-ce
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "plane"
  RABBITMQ_DEFAULT_PASS: "plane"
