apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo-config
  labels:
    app.kubernetes.io/name: nginx-demo
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location = /api/health {
            access_log off;
            default_type application/json;
            return 200 '{"status":"UP","message":"healthy"}\n';
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
